### ISSUE TITLE
validation

### ISSUE THREAD

**Issue by DavidWilliamsQA** [maharjanmilan/contact-form#1]
Hi, 
when I am implementing your code in my own project, I can't seem to figure out which part of the code allows the red exclamation mark to appear when they don't fill in a certain field. The image below is what keeps coming up instead of the exclamation marks and I can't figure out why. Please kindly direct me on what to do. Thank you
![image](https://user-images.githubusercontent.com/60790661/132520165-8f4115dc-bf04-46d1-b174-6b1ff1dc314c.png)

**Comment by maharjanmilan** [comment]
Are you correctly including the font awesome css file in the header?
`<link rel="stylesheet" type="text/css" href="fonts/font-awesome-4.7.0/css/font-awesome.min.css">`

**Comment by DavidWilliamsQA** [comment]
ahh yes that was the missing bit. thanks
